/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WikiRouteImport } from './routes/wiki'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedWikiBrowseRouteImport } from './routes/_protected.wiki-browse'
import { Route as ProtectedSuperAdminRouteImport } from './routes/_protected.super-admin'
import { Route as ProtectedShareRequestsRouteImport } from './routes/_protected.share-requests'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected.settings'
import { Route as ProtectedSearchRouteImport } from './routes/_protected.search'
import { Route as ProtectedOrganizationsRouteImport } from './routes/_protected.organizations'
import { Route as ProtectedHelpRouteImport } from './routes/_protected.help'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected.dashboard'
import { Route as ProtectedConsentRouteImport } from './routes/_protected.consent'
import { Route as ProtectedConnectRouteImport } from './routes/_protected.connect'
import { Route as ProtectedCliAuthRouteImport } from './routes/_protected.cli-auth'
import { Route as ProtectedApiKeysRouteImport } from './routes/_protected.api-keys'
import { Route as ProtectedAgentsRouteImport } from './routes/_protected.agents'
import { Route as ProtectedAccountRouteImport } from './routes/_protected.account'
import { Route as MarketingExploreRouteImport } from './routes/_marketing.explore'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as ProtectedWikiBrowseIndexRouteImport } from './routes/_protected.wiki-browse.index'
import { Route as ProtectedSuperAdminIndexRouteImport } from './routes/_protected.super-admin.index'
import { Route as ProtectedOrganizationsIndexRouteImport } from './routes/_protected.organizations.index'
import { Route as ProtectedAgentsIndexRouteImport } from './routes/_protected.agents.index'
import { Route as ProtectedWikiBrowseSourcesRouteImport } from './routes/_protected.wiki-browse.sources'
import { Route as ProtectedWikiBrowseNewRouteImport } from './routes/_protected.wiki-browse.new'
import { Route as ProtectedWikiBrowseLogRouteImport } from './routes/_protected.wiki-browse.log'
import { Route as ProtectedWikiBrowseHistoryRouteImport } from './routes/_protected.wiki-browse.history'
import { Route as ProtectedWikiBrowseGraphRouteImport } from './routes/_protected.wiki-browse.graph'
import { Route as ProtectedWikiBrowseSlugRouteImport } from './routes/_protected.wiki-browse.$slug'
import { Route as ProtectedSuperAdminUsersRouteImport } from './routes/_protected.super-admin.users'
import { Route as ProtectedSuperAdminOrganizationsRouteImport } from './routes/_protected.super-admin.organizations'
import { Route as ProtectedSuperAdminModerationRouteImport } from './routes/_protected.super-admin.moderation'
import { Route as ProtectedSuperAdminDomainsRouteImport } from './routes/_protected.super-admin.domains'
import { Route as ProtectedSuperAdminAuditRouteImport } from './routes/_protected.super-admin.audit'
import { Route as ProtectedSuperAdminAgentsRouteImport } from './routes/_protected.super-admin.agents'
import { Route as ProtectedSolutionsIdRouteImport } from './routes/_protected.solutions.$id'
import { Route as ProtectedOrganizationsSlugRouteImport } from './routes/_protected.organizations.$slug'
import { Route as ProtectedOrgSettingsSlugRouteImport } from './routes/_protected.org-settings.$slug'
import { Route as ProtectedIssuesIdRouteImport } from './routes/_protected.issues.$id'
import { Route as ProtectedAgentsSlugRouteImport } from './routes/_protected.agents.$slug'
import { Route as MarketingExploreAgentsRouteImport } from './routes/_marketing.explore_.agents'
import { Route as ProtectedWikiBrowseSlugIndexRouteImport } from './routes/_protected.wiki-browse.$slug.index'
import { Route as MarketingExploreAgentsIndexRouteImport } from './routes/_marketing.explore_.agents.index'
import { Route as ProtectedWikiBrowseSlugHistoryRouteImport } from './routes/_protected.wiki-browse.$slug.history'
import { Route as ProtectedWikiBrowseSlugEditRouteImport } from './routes/_protected.wiki-browse.$slug.edit'
import { Route as ProtectedSuperAdminUsersUserIdRouteImport } from './routes/_protected.super-admin.users_.$userId'
import { Route as ProtectedSuperAdminOrganizationsOrgIdRouteImport } from './routes/_protected.super-admin.organizations_.$orgId'
import { Route as ProtectedSuperAdminAgentsAgentIdRouteImport } from './routes/_protected.super-admin.agents_.$agentId'
import { Route as MarketingExploreIssuesIdRouteImport } from './routes/_marketing.explore_.issues.$id'
import { Route as MarketingExploreAgentsSlugRouteImport } from './routes/_marketing.explore_.agents.$slug'

const WikiRoute = WikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedWikiBrowseRoute = ProtectedWikiBrowseRouteImport.update({
  id: '/wiki-browse',
  path: '/wiki-browse',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSuperAdminRoute = ProtectedSuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedShareRequestsRoute = ProtectedShareRequestsRouteImport.update({
  id: '/share-requests',
  path: '/share-requests',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSearchRoute = ProtectedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrganizationsRoute = ProtectedOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHelpRoute = ProtectedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedConsentRoute = ProtectedConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedConnectRoute = ProtectedConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCliAuthRoute = ProtectedCliAuthRouteImport.update({
  id: '/cli-auth',
  path: '/cli-auth',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedApiKeysRoute = ProtectedApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAgentsRoute = ProtectedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAccountRoute = ProtectedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ProtectedRoute,
} as any)
const MarketingExploreRoute = MarketingExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => MarketingRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedWikiBrowseIndexRoute =
  ProtectedWikiBrowseIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedWikiBrowseRoute,
  } as any)
const ProtectedSuperAdminIndexRoute =
  ProtectedSuperAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedSuperAdminRoute,
  } as any)
const ProtectedOrganizationsIndexRoute =
  ProtectedOrganizationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrganizationsRoute,
  } as any)
const ProtectedAgentsIndexRoute = ProtectedAgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAgentsRoute,
} as any)
const ProtectedWikiBrowseSourcesRoute =
  ProtectedWikiBrowseSourcesRouteImport.update({
    id: '/sources',
    path: '/sources',
    getParentRoute: () => ProtectedWikiBrowseRoute,
  } as any)
const ProtectedWikiBrowseNewRoute = ProtectedWikiBrowseNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProtectedWikiBrowseRoute,
} as any)
const ProtectedWikiBrowseLogRoute = ProtectedWikiBrowseLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => ProtectedWikiBrowseRoute,
} as any)
const ProtectedWikiBrowseHistoryRoute =
  ProtectedWikiBrowseHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => ProtectedWikiBrowseRoute,
  } as any)
const ProtectedWikiBrowseGraphRoute =
  ProtectedWikiBrowseGraphRouteImport.update({
    id: '/graph',
    path: '/graph',
    getParentRoute: () => ProtectedWikiBrowseRoute,
  } as any)
const ProtectedWikiBrowseSlugRoute = ProtectedWikiBrowseSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProtectedWikiBrowseRoute,
} as any)
const ProtectedSuperAdminUsersRoute =
  ProtectedSuperAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => ProtectedSuperAdminRoute,
  } as any)
const ProtectedSuperAdminOrganizationsRoute =
  ProtectedSuperAdminOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => ProtectedSuperAdminRoute,
  } as any)
const ProtectedSuperAdminModerationRoute =
  ProtectedSuperAdminModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => ProtectedSuperAdminRoute,
  } as any)
const ProtectedSuperAdminDomainsRoute =
  ProtectedSuperAdminDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => ProtectedSuperAdminRoute,
  } as any)
const ProtectedSuperAdminAuditRoute =
  ProtectedSuperAdminAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => ProtectedSuperAdminRoute,
  } as any)
const ProtectedSuperAdminAgentsRoute =
  ProtectedSuperAdminAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => ProtectedSuperAdminRoute,
  } as any)
const ProtectedSolutionsIdRoute = ProtectedSolutionsIdRouteImport.update({
  id: '/solutions/$id',
  path: '/solutions/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrganizationsSlugRoute =
  ProtectedOrganizationsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => ProtectedOrganizationsRoute,
  } as any)
const ProtectedOrgSettingsSlugRoute =
  ProtectedOrgSettingsSlugRouteImport.update({
    id: '/org-settings/$slug',
    path: '/org-settings/$slug',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedIssuesIdRoute = ProtectedIssuesIdRouteImport.update({
  id: '/issues/$id',
  path: '/issues/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAgentsSlugRoute = ProtectedAgentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProtectedAgentsRoute,
} as any)
const MarketingExploreAgentsRoute = MarketingExploreAgentsRouteImport.update({
  id: '/explore_/agents',
  path: '/explore/agents',
  getParentRoute: () => MarketingRoute,
} as any)
const ProtectedWikiBrowseSlugIndexRoute =
  ProtectedWikiBrowseSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedWikiBrowseSlugRoute,
  } as any)
const MarketingExploreAgentsIndexRoute =
  MarketingExploreAgentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MarketingExploreAgentsRoute,
  } as any)
const ProtectedWikiBrowseSlugHistoryRoute =
  ProtectedWikiBrowseSlugHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => ProtectedWikiBrowseSlugRoute,
  } as any)
const ProtectedWikiBrowseSlugEditRoute =
  ProtectedWikiBrowseSlugEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => ProtectedWikiBrowseSlugRoute,
  } as any)
const ProtectedSuperAdminUsersUserIdRoute =
  ProtectedSuperAdminUsersUserIdRouteImport.update({
    id: '/users_/$userId',
    path: '/users/$userId',
    getParentRoute: () => ProtectedSuperAdminRoute,
  } as any)
const ProtectedSuperAdminOrganizationsOrgIdRoute =
  ProtectedSuperAdminOrganizationsOrgIdRouteImport.update({
    id: '/organizations_/$orgId',
    path: '/organizations/$orgId',
    getParentRoute: () => ProtectedSuperAdminRoute,
  } as any)
const ProtectedSuperAdminAgentsAgentIdRoute =
  ProtectedSuperAdminAgentsAgentIdRouteImport.update({
    id: '/agents_/$agentId',
    path: '/agents/$agentId',
    getParentRoute: () => ProtectedSuperAdminRoute,
  } as any)
const MarketingExploreIssuesIdRoute =
  MarketingExploreIssuesIdRouteImport.update({
    id: '/explore_/issues/$id',
    path: '/explore/issues/$id',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingExploreAgentsSlugRoute =
  MarketingExploreAgentsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => MarketingExploreAgentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/wiki': typeof WikiRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/explore': typeof MarketingExploreRoute
  '/account': typeof ProtectedAccountRoute
  '/agents': typeof ProtectedAgentsRouteWithChildren
  '/api-keys': typeof ProtectedApiKeysRoute
  '/cli-auth': typeof ProtectedCliAuthRoute
  '/connect': typeof ProtectedConnectRoute
  '/consent': typeof ProtectedConsentRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/help': typeof ProtectedHelpRoute
  '/organizations': typeof ProtectedOrganizationsRouteWithChildren
  '/search': typeof ProtectedSearchRoute
  '/settings': typeof ProtectedSettingsRoute
  '/share-requests': typeof ProtectedShareRequestsRoute
  '/super-admin': typeof ProtectedSuperAdminRouteWithChildren
  '/wiki-browse': typeof ProtectedWikiBrowseRouteWithChildren
  '/explore/agents': typeof MarketingExploreAgentsRouteWithChildren
  '/agents/$slug': typeof ProtectedAgentsSlugRoute
  '/issues/$id': typeof ProtectedIssuesIdRoute
  '/org-settings/$slug': typeof ProtectedOrgSettingsSlugRoute
  '/organizations/$slug': typeof ProtectedOrganizationsSlugRoute
  '/solutions/$id': typeof ProtectedSolutionsIdRoute
  '/super-admin/agents': typeof ProtectedSuperAdminAgentsRoute
  '/super-admin/audit': typeof ProtectedSuperAdminAuditRoute
  '/super-admin/domains': typeof ProtectedSuperAdminDomainsRoute
  '/super-admin/moderation': typeof ProtectedSuperAdminModerationRoute
  '/super-admin/organizations': typeof ProtectedSuperAdminOrganizationsRoute
  '/super-admin/users': typeof ProtectedSuperAdminUsersRoute
  '/wiki-browse/$slug': typeof ProtectedWikiBrowseSlugRouteWithChildren
  '/wiki-browse/graph': typeof ProtectedWikiBrowseGraphRoute
  '/wiki-browse/history': typeof ProtectedWikiBrowseHistoryRoute
  '/wiki-browse/log': typeof ProtectedWikiBrowseLogRoute
  '/wiki-browse/new': typeof ProtectedWikiBrowseNewRoute
  '/wiki-browse/sources': typeof ProtectedWikiBrowseSourcesRoute
  '/agents/': typeof ProtectedAgentsIndexRoute
  '/organizations/': typeof ProtectedOrganizationsIndexRoute
  '/super-admin/': typeof ProtectedSuperAdminIndexRoute
  '/wiki-browse/': typeof ProtectedWikiBrowseIndexRoute
  '/explore/agents/$slug': typeof MarketingExploreAgentsSlugRoute
  '/explore/issues/$id': typeof MarketingExploreIssuesIdRoute
  '/super-admin/agents/$agentId': typeof ProtectedSuperAdminAgentsAgentIdRoute
  '/super-admin/organizations/$orgId': typeof ProtectedSuperAdminOrganizationsOrgIdRoute
  '/super-admin/users/$userId': typeof ProtectedSuperAdminUsersUserIdRoute
  '/wiki-browse/$slug/edit': typeof ProtectedWikiBrowseSlugEditRoute
  '/wiki-browse/$slug/history': typeof ProtectedWikiBrowseSlugHistoryRoute
  '/explore/agents/': typeof MarketingExploreAgentsIndexRoute
  '/wiki-browse/$slug/': typeof ProtectedWikiBrowseSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/wiki': typeof WikiRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/explore': typeof MarketingExploreRoute
  '/account': typeof ProtectedAccountRoute
  '/api-keys': typeof ProtectedApiKeysRoute
  '/cli-auth': typeof ProtectedCliAuthRoute
  '/connect': typeof ProtectedConnectRoute
  '/consent': typeof ProtectedConsentRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/help': typeof ProtectedHelpRoute
  '/search': typeof ProtectedSearchRoute
  '/settings': typeof ProtectedSettingsRoute
  '/share-requests': typeof ProtectedShareRequestsRoute
  '/agents/$slug': typeof ProtectedAgentsSlugRoute
  '/issues/$id': typeof ProtectedIssuesIdRoute
  '/org-settings/$slug': typeof ProtectedOrgSettingsSlugRoute
  '/organizations/$slug': typeof ProtectedOrganizationsSlugRoute
  '/solutions/$id': typeof ProtectedSolutionsIdRoute
  '/super-admin/agents': typeof ProtectedSuperAdminAgentsRoute
  '/super-admin/audit': typeof ProtectedSuperAdminAuditRoute
  '/super-admin/domains': typeof ProtectedSuperAdminDomainsRoute
  '/super-admin/moderation': typeof ProtectedSuperAdminModerationRoute
  '/super-admin/organizations': typeof ProtectedSuperAdminOrganizationsRoute
  '/super-admin/users': typeof ProtectedSuperAdminUsersRoute
  '/wiki-browse/graph': typeof ProtectedWikiBrowseGraphRoute
  '/wiki-browse/history': typeof ProtectedWikiBrowseHistoryRoute
  '/wiki-browse/log': typeof ProtectedWikiBrowseLogRoute
  '/wiki-browse/new': typeof ProtectedWikiBrowseNewRoute
  '/wiki-browse/sources': typeof ProtectedWikiBrowseSourcesRoute
  '/agents': typeof ProtectedAgentsIndexRoute
  '/organizations': typeof ProtectedOrganizationsIndexRoute
  '/super-admin': typeof ProtectedSuperAdminIndexRoute
  '/wiki-browse': typeof ProtectedWikiBrowseIndexRoute
  '/explore/agents/$slug': typeof MarketingExploreAgentsSlugRoute
  '/explore/issues/$id': typeof MarketingExploreIssuesIdRoute
  '/super-admin/agents/$agentId': typeof ProtectedSuperAdminAgentsAgentIdRoute
  '/super-admin/organizations/$orgId': typeof ProtectedSuperAdminOrganizationsOrgIdRoute
  '/super-admin/users/$userId': typeof ProtectedSuperAdminUsersUserIdRoute
  '/wiki-browse/$slug/edit': typeof ProtectedWikiBrowseSlugEditRoute
  '/wiki-browse/$slug/history': typeof ProtectedWikiBrowseSlugHistoryRoute
  '/explore/agents': typeof MarketingExploreAgentsIndexRoute
  '/wiki-browse/$slug': typeof ProtectedWikiBrowseSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/wiki': typeof WikiRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_marketing/explore': typeof MarketingExploreRoute
  '/_protected/account': typeof ProtectedAccountRoute
  '/_protected/agents': typeof ProtectedAgentsRouteWithChildren
  '/_protected/api-keys': typeof ProtectedApiKeysRoute
  '/_protected/cli-auth': typeof ProtectedCliAuthRoute
  '/_protected/connect': typeof ProtectedConnectRoute
  '/_protected/consent': typeof ProtectedConsentRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/help': typeof ProtectedHelpRoute
  '/_protected/organizations': typeof ProtectedOrganizationsRouteWithChildren
  '/_protected/search': typeof ProtectedSearchRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/share-requests': typeof ProtectedShareRequestsRoute
  '/_protected/super-admin': typeof ProtectedSuperAdminRouteWithChildren
  '/_protected/wiki-browse': typeof ProtectedWikiBrowseRouteWithChildren
  '/_marketing/explore_/agents': typeof MarketingExploreAgentsRouteWithChildren
  '/_protected/agents/$slug': typeof ProtectedAgentsSlugRoute
  '/_protected/issues/$id': typeof ProtectedIssuesIdRoute
  '/_protected/org-settings/$slug': typeof ProtectedOrgSettingsSlugRoute
  '/_protected/organizations/$slug': typeof ProtectedOrganizationsSlugRoute
  '/_protected/solutions/$id': typeof ProtectedSolutionsIdRoute
  '/_protected/super-admin/agents': typeof ProtectedSuperAdminAgentsRoute
  '/_protected/super-admin/audit': typeof ProtectedSuperAdminAuditRoute
  '/_protected/super-admin/domains': typeof ProtectedSuperAdminDomainsRoute
  '/_protected/super-admin/moderation': typeof ProtectedSuperAdminModerationRoute
  '/_protected/super-admin/organizations': typeof ProtectedSuperAdminOrganizationsRoute
  '/_protected/super-admin/users': typeof ProtectedSuperAdminUsersRoute
  '/_protected/wiki-browse/$slug': typeof ProtectedWikiBrowseSlugRouteWithChildren
  '/_protected/wiki-browse/graph': typeof ProtectedWikiBrowseGraphRoute
  '/_protected/wiki-browse/history': typeof ProtectedWikiBrowseHistoryRoute
  '/_protected/wiki-browse/log': typeof ProtectedWikiBrowseLogRoute
  '/_protected/wiki-browse/new': typeof ProtectedWikiBrowseNewRoute
  '/_protected/wiki-browse/sources': typeof ProtectedWikiBrowseSourcesRoute
  '/_protected/agents/': typeof ProtectedAgentsIndexRoute
  '/_protected/organizations/': typeof ProtectedOrganizationsIndexRoute
  '/_protected/super-admin/': typeof ProtectedSuperAdminIndexRoute
  '/_protected/wiki-browse/': typeof ProtectedWikiBrowseIndexRoute
  '/_marketing/explore_/agents/$slug': typeof MarketingExploreAgentsSlugRoute
  '/_marketing/explore_/issues/$id': typeof MarketingExploreIssuesIdRoute
  '/_protected/super-admin/agents_/$agentId': typeof ProtectedSuperAdminAgentsAgentIdRoute
  '/_protected/super-admin/organizations_/$orgId': typeof ProtectedSuperAdminOrganizationsOrgIdRoute
  '/_protected/super-admin/users_/$userId': typeof ProtectedSuperAdminUsersUserIdRoute
  '/_protected/wiki-browse/$slug/edit': typeof ProtectedWikiBrowseSlugEditRoute
  '/_protected/wiki-browse/$slug/history': typeof ProtectedWikiBrowseSlugHistoryRoute
  '/_marketing/explore_/agents/': typeof MarketingExploreAgentsIndexRoute
  '/_protected/wiki-browse/$slug/': typeof ProtectedWikiBrowseSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/privacy'
    | '/terms'
    | '/wiki'
    | '/login'
    | '/signup'
    | '/explore'
    | '/account'
    | '/agents'
    | '/api-keys'
    | '/cli-auth'
    | '/connect'
    | '/consent'
    | '/dashboard'
    | '/help'
    | '/organizations'
    | '/search'
    | '/settings'
    | '/share-requests'
    | '/super-admin'
    | '/wiki-browse'
    | '/explore/agents'
    | '/agents/$slug'
    | '/issues/$id'
    | '/org-settings/$slug'
    | '/organizations/$slug'
    | '/solutions/$id'
    | '/super-admin/agents'
    | '/super-admin/audit'
    | '/super-admin/domains'
    | '/super-admin/moderation'
    | '/super-admin/organizations'
    | '/super-admin/users'
    | '/wiki-browse/$slug'
    | '/wiki-browse/graph'
    | '/wiki-browse/history'
    | '/wiki-browse/log'
    | '/wiki-browse/new'
    | '/wiki-browse/sources'
    | '/agents/'
    | '/organizations/'
    | '/super-admin/'
    | '/wiki-browse/'
    | '/explore/agents/$slug'
    | '/explore/issues/$id'
    | '/super-admin/agents/$agentId'
    | '/super-admin/organizations/$orgId'
    | '/super-admin/users/$userId'
    | '/wiki-browse/$slug/edit'
    | '/wiki-browse/$slug/history'
    | '/explore/agents/'
    | '/wiki-browse/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/privacy'
    | '/terms'
    | '/wiki'
    | '/login'
    | '/signup'
    | '/explore'
    | '/account'
    | '/api-keys'
    | '/cli-auth'
    | '/connect'
    | '/consent'
    | '/dashboard'
    | '/help'
    | '/search'
    | '/settings'
    | '/share-requests'
    | '/agents/$slug'
    | '/issues/$id'
    | '/org-settings/$slug'
    | '/organizations/$slug'
    | '/solutions/$id'
    | '/super-admin/agents'
    | '/super-admin/audit'
    | '/super-admin/domains'
    | '/super-admin/moderation'
    | '/super-admin/organizations'
    | '/super-admin/users'
    | '/wiki-browse/graph'
    | '/wiki-browse/history'
    | '/wiki-browse/log'
    | '/wiki-browse/new'
    | '/wiki-browse/sources'
    | '/agents'
    | '/organizations'
    | '/super-admin'
    | '/wiki-browse'
    | '/explore/agents/$slug'
    | '/explore/issues/$id'
    | '/super-admin/agents/$agentId'
    | '/super-admin/organizations/$orgId'
    | '/super-admin/users/$userId'
    | '/wiki-browse/$slug/edit'
    | '/wiki-browse/$slug/history'
    | '/explore/agents'
    | '/wiki-browse/$slug'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_marketing'
    | '/_protected'
    | '/faq'
    | '/privacy'
    | '/terms'
    | '/wiki'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_marketing/explore'
    | '/_protected/account'
    | '/_protected/agents'
    | '/_protected/api-keys'
    | '/_protected/cli-auth'
    | '/_protected/connect'
    | '/_protected/consent'
    | '/_protected/dashboard'
    | '/_protected/help'
    | '/_protected/organizations'
    | '/_protected/search'
    | '/_protected/settings'
    | '/_protected/share-requests'
    | '/_protected/super-admin'
    | '/_protected/wiki-browse'
    | '/_marketing/explore_/agents'
    | '/_protected/agents/$slug'
    | '/_protected/issues/$id'
    | '/_protected/org-settings/$slug'
    | '/_protected/organizations/$slug'
    | '/_protected/solutions/$id'
    | '/_protected/super-admin/agents'
    | '/_protected/super-admin/audit'
    | '/_protected/super-admin/domains'
    | '/_protected/super-admin/moderation'
    | '/_protected/super-admin/organizations'
    | '/_protected/super-admin/users'
    | '/_protected/wiki-browse/$slug'
    | '/_protected/wiki-browse/graph'
    | '/_protected/wiki-browse/history'
    | '/_protected/wiki-browse/log'
    | '/_protected/wiki-browse/new'
    | '/_protected/wiki-browse/sources'
    | '/_protected/agents/'
    | '/_protected/organizations/'
    | '/_protected/super-admin/'
    | '/_protected/wiki-browse/'
    | '/_marketing/explore_/agents/$slug'
    | '/_marketing/explore_/issues/$id'
    | '/_protected/super-admin/agents_/$agentId'
    | '/_protected/super-admin/organizations_/$orgId'
    | '/_protected/super-admin/users_/$userId'
    | '/_protected/wiki-browse/$slug/edit'
    | '/_protected/wiki-browse/$slug/history'
    | '/_marketing/explore_/agents/'
    | '/_protected/wiki-browse/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  WikiRoute: typeof WikiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/wiki-browse': {
      id: '/_protected/wiki-browse'
      path: '/wiki-browse'
      fullPath: '/wiki-browse'
      preLoaderRoute: typeof ProtectedWikiBrowseRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/super-admin': {
      id: '/_protected/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof ProtectedSuperAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/share-requests': {
      id: '/_protected/share-requests'
      path: '/share-requests'
      fullPath: '/share-requests'
      preLoaderRoute: typeof ProtectedShareRequestsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/search': {
      id: '/_protected/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof ProtectedSearchRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/organizations': {
      id: '/_protected/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof ProtectedOrganizationsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/help': {
      id: '/_protected/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof ProtectedHelpRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/consent': {
      id: '/_protected/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ProtectedConsentRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/connect': {
      id: '/_protected/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ProtectedConnectRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/cli-auth': {
      id: '/_protected/cli-auth'
      path: '/cli-auth'
      fullPath: '/cli-auth'
      preLoaderRoute: typeof ProtectedCliAuthRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/api-keys': {
      id: '/_protected/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ProtectedApiKeysRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/agents': {
      id: '/_protected/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof ProtectedAgentsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/account': {
      id: '/_protected/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ProtectedAccountRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_marketing/explore': {
      id: '/_marketing/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof MarketingExploreRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/wiki-browse/': {
      id: '/_protected/wiki-browse/'
      path: '/'
      fullPath: '/wiki-browse/'
      preLoaderRoute: typeof ProtectedWikiBrowseIndexRouteImport
      parentRoute: typeof ProtectedWikiBrowseRoute
    }
    '/_protected/super-admin/': {
      id: '/_protected/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof ProtectedSuperAdminIndexRouteImport
      parentRoute: typeof ProtectedSuperAdminRoute
    }
    '/_protected/organizations/': {
      id: '/_protected/organizations/'
      path: '/'
      fullPath: '/organizations/'
      preLoaderRoute: typeof ProtectedOrganizationsIndexRouteImport
      parentRoute: typeof ProtectedOrganizationsRoute
    }
    '/_protected/agents/': {
      id: '/_protected/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof ProtectedAgentsIndexRouteImport
      parentRoute: typeof ProtectedAgentsRoute
    }
    '/_protected/wiki-browse/sources': {
      id: '/_protected/wiki-browse/sources'
      path: '/sources'
      fullPath: '/wiki-browse/sources'
      preLoaderRoute: typeof ProtectedWikiBrowseSourcesRouteImport
      parentRoute: typeof ProtectedWikiBrowseRoute
    }
    '/_protected/wiki-browse/new': {
      id: '/_protected/wiki-browse/new'
      path: '/new'
      fullPath: '/wiki-browse/new'
      preLoaderRoute: typeof ProtectedWikiBrowseNewRouteImport
      parentRoute: typeof ProtectedWikiBrowseRoute
    }
    '/_protected/wiki-browse/log': {
      id: '/_protected/wiki-browse/log'
      path: '/log'
      fullPath: '/wiki-browse/log'
      preLoaderRoute: typeof ProtectedWikiBrowseLogRouteImport
      parentRoute: typeof ProtectedWikiBrowseRoute
    }
    '/_protected/wiki-browse/history': {
      id: '/_protected/wiki-browse/history'
      path: '/history'
      fullPath: '/wiki-browse/history'
      preLoaderRoute: typeof ProtectedWikiBrowseHistoryRouteImport
      parentRoute: typeof ProtectedWikiBrowseRoute
    }
    '/_protected/wiki-browse/graph': {
      id: '/_protected/wiki-browse/graph'
      path: '/graph'
      fullPath: '/wiki-browse/graph'
      preLoaderRoute: typeof ProtectedWikiBrowseGraphRouteImport
      parentRoute: typeof ProtectedWikiBrowseRoute
    }
    '/_protected/wiki-browse/$slug': {
      id: '/_protected/wiki-browse/$slug'
      path: '/$slug'
      fullPath: '/wiki-browse/$slug'
      preLoaderRoute: typeof ProtectedWikiBrowseSlugRouteImport
      parentRoute: typeof ProtectedWikiBrowseRoute
    }
    '/_protected/super-admin/users': {
      id: '/_protected/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof ProtectedSuperAdminUsersRouteImport
      parentRoute: typeof ProtectedSuperAdminRoute
    }
    '/_protected/super-admin/organizations': {
      id: '/_protected/super-admin/organizations'
      path: '/organizations'
      fullPath: '/super-admin/organizations'
      preLoaderRoute: typeof ProtectedSuperAdminOrganizationsRouteImport
      parentRoute: typeof ProtectedSuperAdminRoute
    }
    '/_protected/super-admin/moderation': {
      id: '/_protected/super-admin/moderation'
      path: '/moderation'
      fullPath: '/super-admin/moderation'
      preLoaderRoute: typeof ProtectedSuperAdminModerationRouteImport
      parentRoute: typeof ProtectedSuperAdminRoute
    }
    '/_protected/super-admin/domains': {
      id: '/_protected/super-admin/domains'
      path: '/domains'
      fullPath: '/super-admin/domains'
      preLoaderRoute: typeof ProtectedSuperAdminDomainsRouteImport
      parentRoute: typeof ProtectedSuperAdminRoute
    }
    '/_protected/super-admin/audit': {
      id: '/_protected/super-admin/audit'
      path: '/audit'
      fullPath: '/super-admin/audit'
      preLoaderRoute: typeof ProtectedSuperAdminAuditRouteImport
      parentRoute: typeof ProtectedSuperAdminRoute
    }
    '/_protected/super-admin/agents': {
      id: '/_protected/super-admin/agents'
      path: '/agents'
      fullPath: '/super-admin/agents'
      preLoaderRoute: typeof ProtectedSuperAdminAgentsRouteImport
      parentRoute: typeof ProtectedSuperAdminRoute
    }
    '/_protected/solutions/$id': {
      id: '/_protected/solutions/$id'
      path: '/solutions/$id'
      fullPath: '/solutions/$id'
      preLoaderRoute: typeof ProtectedSolutionsIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/organizations/$slug': {
      id: '/_protected/organizations/$slug'
      path: '/$slug'
      fullPath: '/organizations/$slug'
      preLoaderRoute: typeof ProtectedOrganizationsSlugRouteImport
      parentRoute: typeof ProtectedOrganizationsRoute
    }
    '/_protected/org-settings/$slug': {
      id: '/_protected/org-settings/$slug'
      path: '/org-settings/$slug'
      fullPath: '/org-settings/$slug'
      preLoaderRoute: typeof ProtectedOrgSettingsSlugRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/issues/$id': {
      id: '/_protected/issues/$id'
      path: '/issues/$id'
      fullPath: '/issues/$id'
      preLoaderRoute: typeof ProtectedIssuesIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/agents/$slug': {
      id: '/_protected/agents/$slug'
      path: '/$slug'
      fullPath: '/agents/$slug'
      preLoaderRoute: typeof ProtectedAgentsSlugRouteImport
      parentRoute: typeof ProtectedAgentsRoute
    }
    '/_marketing/explore_/agents': {
      id: '/_marketing/explore_/agents'
      path: '/explore/agents'
      fullPath: '/explore/agents'
      preLoaderRoute: typeof MarketingExploreAgentsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_protected/wiki-browse/$slug/': {
      id: '/_protected/wiki-browse/$slug/'
      path: '/'
      fullPath: '/wiki-browse/$slug/'
      preLoaderRoute: typeof ProtectedWikiBrowseSlugIndexRouteImport
      parentRoute: typeof ProtectedWikiBrowseSlugRoute
    }
    '/_marketing/explore_/agents/': {
      id: '/_marketing/explore_/agents/'
      path: '/'
      fullPath: '/explore/agents/'
      preLoaderRoute: typeof MarketingExploreAgentsIndexRouteImport
      parentRoute: typeof MarketingExploreAgentsRoute
    }
    '/_protected/wiki-browse/$slug/history': {
      id: '/_protected/wiki-browse/$slug/history'
      path: '/history'
      fullPath: '/wiki-browse/$slug/history'
      preLoaderRoute: typeof ProtectedWikiBrowseSlugHistoryRouteImport
      parentRoute: typeof ProtectedWikiBrowseSlugRoute
    }
    '/_protected/wiki-browse/$slug/edit': {
      id: '/_protected/wiki-browse/$slug/edit'
      path: '/edit'
      fullPath: '/wiki-browse/$slug/edit'
      preLoaderRoute: typeof ProtectedWikiBrowseSlugEditRouteImport
      parentRoute: typeof ProtectedWikiBrowseSlugRoute
    }
    '/_protected/super-admin/users_/$userId': {
      id: '/_protected/super-admin/users_/$userId'
      path: '/users/$userId'
      fullPath: '/super-admin/users/$userId'
      preLoaderRoute: typeof ProtectedSuperAdminUsersUserIdRouteImport
      parentRoute: typeof ProtectedSuperAdminRoute
    }
    '/_protected/super-admin/organizations_/$orgId': {
      id: '/_protected/super-admin/organizations_/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/super-admin/organizations/$orgId'
      preLoaderRoute: typeof ProtectedSuperAdminOrganizationsOrgIdRouteImport
      parentRoute: typeof ProtectedSuperAdminRoute
    }
    '/_protected/super-admin/agents_/$agentId': {
      id: '/_protected/super-admin/agents_/$agentId'
      path: '/agents/$agentId'
      fullPath: '/super-admin/agents/$agentId'
      preLoaderRoute: typeof ProtectedSuperAdminAgentsAgentIdRouteImport
      parentRoute: typeof ProtectedSuperAdminRoute
    }
    '/_marketing/explore_/issues/$id': {
      id: '/_marketing/explore_/issues/$id'
      path: '/explore/issues/$id'
      fullPath: '/explore/issues/$id'
      preLoaderRoute: typeof MarketingExploreIssuesIdRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/explore_/agents/$slug': {
      id: '/_marketing/explore_/agents/$slug'
      path: '/$slug'
      fullPath: '/explore/agents/$slug'
      preLoaderRoute: typeof MarketingExploreAgentsSlugRouteImport
      parentRoute: typeof MarketingExploreAgentsRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MarketingExploreAgentsRouteChildren {
  MarketingExploreAgentsSlugRoute: typeof MarketingExploreAgentsSlugRoute
  MarketingExploreAgentsIndexRoute: typeof MarketingExploreAgentsIndexRoute
}

const MarketingExploreAgentsRouteChildren: MarketingExploreAgentsRouteChildren =
  {
    MarketingExploreAgentsSlugRoute: MarketingExploreAgentsSlugRoute,
    MarketingExploreAgentsIndexRoute: MarketingExploreAgentsIndexRoute,
  }

const MarketingExploreAgentsRouteWithChildren =
  MarketingExploreAgentsRoute._addFileChildren(
    MarketingExploreAgentsRouteChildren,
  )

interface MarketingRouteChildren {
  MarketingExploreRoute: typeof MarketingExploreRoute
  MarketingExploreAgentsRoute: typeof MarketingExploreAgentsRouteWithChildren
  MarketingExploreIssuesIdRoute: typeof MarketingExploreIssuesIdRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingExploreRoute: MarketingExploreRoute,
  MarketingExploreAgentsRoute: MarketingExploreAgentsRouteWithChildren,
  MarketingExploreIssuesIdRoute: MarketingExploreIssuesIdRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface ProtectedAgentsRouteChildren {
  ProtectedAgentsSlugRoute: typeof ProtectedAgentsSlugRoute
  ProtectedAgentsIndexRoute: typeof ProtectedAgentsIndexRoute
}

const ProtectedAgentsRouteChildren: ProtectedAgentsRouteChildren = {
  ProtectedAgentsSlugRoute: ProtectedAgentsSlugRoute,
  ProtectedAgentsIndexRoute: ProtectedAgentsIndexRoute,
}

const ProtectedAgentsRouteWithChildren = ProtectedAgentsRoute._addFileChildren(
  ProtectedAgentsRouteChildren,
)

interface ProtectedOrganizationsRouteChildren {
  ProtectedOrganizationsSlugRoute: typeof ProtectedOrganizationsSlugRoute
  ProtectedOrganizationsIndexRoute: typeof ProtectedOrganizationsIndexRoute
}

const ProtectedOrganizationsRouteChildren: ProtectedOrganizationsRouteChildren =
  {
    ProtectedOrganizationsSlugRoute: ProtectedOrganizationsSlugRoute,
    ProtectedOrganizationsIndexRoute: ProtectedOrganizationsIndexRoute,
  }

const ProtectedOrganizationsRouteWithChildren =
  ProtectedOrganizationsRoute._addFileChildren(
    ProtectedOrganizationsRouteChildren,
  )

interface ProtectedSuperAdminRouteChildren {
  ProtectedSuperAdminAgentsRoute: typeof ProtectedSuperAdminAgentsRoute
  ProtectedSuperAdminAuditRoute: typeof ProtectedSuperAdminAuditRoute
  ProtectedSuperAdminDomainsRoute: typeof ProtectedSuperAdminDomainsRoute
  ProtectedSuperAdminModerationRoute: typeof ProtectedSuperAdminModerationRoute
  ProtectedSuperAdminOrganizationsRoute: typeof ProtectedSuperAdminOrganizationsRoute
  ProtectedSuperAdminUsersRoute: typeof ProtectedSuperAdminUsersRoute
  ProtectedSuperAdminIndexRoute: typeof ProtectedSuperAdminIndexRoute
  ProtectedSuperAdminAgentsAgentIdRoute: typeof ProtectedSuperAdminAgentsAgentIdRoute
  ProtectedSuperAdminOrganizationsOrgIdRoute: typeof ProtectedSuperAdminOrganizationsOrgIdRoute
  ProtectedSuperAdminUsersUserIdRoute: typeof ProtectedSuperAdminUsersUserIdRoute
}

const ProtectedSuperAdminRouteChildren: ProtectedSuperAdminRouteChildren = {
  ProtectedSuperAdminAgentsRoute: ProtectedSuperAdminAgentsRoute,
  ProtectedSuperAdminAuditRoute: ProtectedSuperAdminAuditRoute,
  ProtectedSuperAdminDomainsRoute: ProtectedSuperAdminDomainsRoute,
  ProtectedSuperAdminModerationRoute: ProtectedSuperAdminModerationRoute,
  ProtectedSuperAdminOrganizationsRoute: ProtectedSuperAdminOrganizationsRoute,
  ProtectedSuperAdminUsersRoute: ProtectedSuperAdminUsersRoute,
  ProtectedSuperAdminIndexRoute: ProtectedSuperAdminIndexRoute,
  ProtectedSuperAdminAgentsAgentIdRoute: ProtectedSuperAdminAgentsAgentIdRoute,
  ProtectedSuperAdminOrganizationsOrgIdRoute:
    ProtectedSuperAdminOrganizationsOrgIdRoute,
  ProtectedSuperAdminUsersUserIdRoute: ProtectedSuperAdminUsersUserIdRoute,
}

const ProtectedSuperAdminRouteWithChildren =
  ProtectedSuperAdminRoute._addFileChildren(ProtectedSuperAdminRouteChildren)

interface ProtectedWikiBrowseSlugRouteChildren {
  ProtectedWikiBrowseSlugEditRoute: typeof ProtectedWikiBrowseSlugEditRoute
  ProtectedWikiBrowseSlugHistoryRoute: typeof ProtectedWikiBrowseSlugHistoryRoute
  ProtectedWikiBrowseSlugIndexRoute: typeof ProtectedWikiBrowseSlugIndexRoute
}

const ProtectedWikiBrowseSlugRouteChildren: ProtectedWikiBrowseSlugRouteChildren =
  {
    ProtectedWikiBrowseSlugEditRoute: ProtectedWikiBrowseSlugEditRoute,
    ProtectedWikiBrowseSlugHistoryRoute: ProtectedWikiBrowseSlugHistoryRoute,
    ProtectedWikiBrowseSlugIndexRoute: ProtectedWikiBrowseSlugIndexRoute,
  }

const ProtectedWikiBrowseSlugRouteWithChildren =
  ProtectedWikiBrowseSlugRoute._addFileChildren(
    ProtectedWikiBrowseSlugRouteChildren,
  )

interface ProtectedWikiBrowseRouteChildren {
  ProtectedWikiBrowseSlugRoute: typeof ProtectedWikiBrowseSlugRouteWithChildren
  ProtectedWikiBrowseGraphRoute: typeof ProtectedWikiBrowseGraphRoute
  ProtectedWikiBrowseHistoryRoute: typeof ProtectedWikiBrowseHistoryRoute
  ProtectedWikiBrowseLogRoute: typeof ProtectedWikiBrowseLogRoute
  ProtectedWikiBrowseNewRoute: typeof ProtectedWikiBrowseNewRoute
  ProtectedWikiBrowseSourcesRoute: typeof ProtectedWikiBrowseSourcesRoute
  ProtectedWikiBrowseIndexRoute: typeof ProtectedWikiBrowseIndexRoute
}

const ProtectedWikiBrowseRouteChildren: ProtectedWikiBrowseRouteChildren = {
  ProtectedWikiBrowseSlugRoute: ProtectedWikiBrowseSlugRouteWithChildren,
  ProtectedWikiBrowseGraphRoute: ProtectedWikiBrowseGraphRoute,
  ProtectedWikiBrowseHistoryRoute: ProtectedWikiBrowseHistoryRoute,
  ProtectedWikiBrowseLogRoute: ProtectedWikiBrowseLogRoute,
  ProtectedWikiBrowseNewRoute: ProtectedWikiBrowseNewRoute,
  ProtectedWikiBrowseSourcesRoute: ProtectedWikiBrowseSourcesRoute,
  ProtectedWikiBrowseIndexRoute: ProtectedWikiBrowseIndexRoute,
}

const ProtectedWikiBrowseRouteWithChildren =
  ProtectedWikiBrowseRoute._addFileChildren(ProtectedWikiBrowseRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAccountRoute: typeof ProtectedAccountRoute
  ProtectedAgentsRoute: typeof ProtectedAgentsRouteWithChildren
  ProtectedApiKeysRoute: typeof ProtectedApiKeysRoute
  ProtectedCliAuthRoute: typeof ProtectedCliAuthRoute
  ProtectedConnectRoute: typeof ProtectedConnectRoute
  ProtectedConsentRoute: typeof ProtectedConsentRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedHelpRoute: typeof ProtectedHelpRoute
  ProtectedOrganizationsRoute: typeof ProtectedOrganizationsRouteWithChildren
  ProtectedSearchRoute: typeof ProtectedSearchRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedShareRequestsRoute: typeof ProtectedShareRequestsRoute
  ProtectedSuperAdminRoute: typeof ProtectedSuperAdminRouteWithChildren
  ProtectedWikiBrowseRoute: typeof ProtectedWikiBrowseRouteWithChildren
  ProtectedIssuesIdRoute: typeof ProtectedIssuesIdRoute
  ProtectedOrgSettingsSlugRoute: typeof ProtectedOrgSettingsSlugRoute
  ProtectedSolutionsIdRoute: typeof ProtectedSolutionsIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAccountRoute: ProtectedAccountRoute,
  ProtectedAgentsRoute: ProtectedAgentsRouteWithChildren,
  ProtectedApiKeysRoute: ProtectedApiKeysRoute,
  ProtectedCliAuthRoute: ProtectedCliAuthRoute,
  ProtectedConnectRoute: ProtectedConnectRoute,
  ProtectedConsentRoute: ProtectedConsentRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedHelpRoute: ProtectedHelpRoute,
  ProtectedOrganizationsRoute: ProtectedOrganizationsRouteWithChildren,
  ProtectedSearchRoute: ProtectedSearchRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedShareRequestsRoute: ProtectedShareRequestsRoute,
  ProtectedSuperAdminRoute: ProtectedSuperAdminRouteWithChildren,
  ProtectedWikiBrowseRoute: ProtectedWikiBrowseRouteWithChildren,
  ProtectedIssuesIdRoute: ProtectedIssuesIdRoute,
  ProtectedOrgSettingsSlugRoute: ProtectedOrgSettingsSlugRoute,
  ProtectedSolutionsIdRoute: ProtectedSolutionsIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  WikiRoute: WikiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
